@startuml

participant Bruker
participant Applikasjon
participant Mobiltjenesteleverandør
participant APIleverandør

Bruker -> Applikasjon: Åpner reiseplanlegger
activate Applikasjon
Applikasjon -> Mobiltjenesteleverandør: getUserLocation()
activate Mobiltjenesteleverandør
Mobiltjenesteleverandør --> Applikasjon: brukerlokasjon
deactivate Mobiltjenesteleverandør

Applikasjon -> APIleverandør: Fetch Weather Data
activate APIleverandør
APIleverandør --> Applikasjon: Return Weather Data
deactivate APIleverandør

Applikasjon --> Bruker: Display Weather and Storm Forecast

Bruker -> Applikasjon: Click on Storm 
Applikasjon --> Bruker: Display Recommendations for Marine Travel

deactivate Applikasjon
@enduml
